DROP TRIGGER IF EXISTS trg_timeline_updated ON election_timeline;
DROP TRIGGER IF EXISTS trg_events_updated ON events;
DROP TRIGGER IF EXISTS trg_news_sources_updated ON news_sources;
DROP TRIGGER IF EXISTS trg_sources_updated ON sources;
DROP TRIGGER IF EXISTS trg_integrity_flags_updated ON integrity_flags;
DROP TRIGGER IF EXISTS trg_court_cases_updated ON court_cases;
DROP TRIGGER IF EXISTS trg_promises_updated ON promises;
DROP TRIGGER IF EXISTS trg_manifestos_updated ON manifestos;
DROP TRIGGER IF EXISTS trg_candidacies_updated ON candidacies;
DROP TRIGGER IF EXISTS trg_elections_updated ON elections;
DROP TRIGGER IF EXISTS trg_coalitions_updated ON coalitions;
DROP TRIGGER IF EXISTS trg_parties_updated ON political_parties;
DROP TRIGGER IF EXISTS trg_politicians_updated ON politicians;

DROP FUNCTION IF EXISTS update_updated_at();

DROP TABLE IF EXISTS election_timeline;
DROP TABLE IF EXISTS event_participants;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS sentiment_snapshots;
DROP TABLE IF EXISTS social_post_mentions;
DROP TABLE IF EXISTS social_posts;
DROP TABLE IF EXISTS article_politician_mentions;
DROP TABLE IF EXISTS news_articles;
DROP TABLE IF EXISTS news_sources;
DROP TABLE IF EXISTS affiliations;
DROP TABLE IF EXISTS controversies;
DROP TABLE IF EXISTS achievements;
DROP TABLE IF EXISTS parliamentary_attendance;
DROP TABLE IF EXISTS voting_records;
DROP TABLE IF EXISTS integrity_flags;
DROP TABLE IF EXISTS asset_declarations;
DROP TABLE IF EXISTS court_cases;
DROP TABLE IF EXISTS promises;
DROP TABLE IF EXISTS policy_positions;
DROP TABLE IF EXISTS manifestos;
DROP TABLE IF EXISTS election_results;
DROP TABLE IF EXISTS candidacies;
DROP TABLE IF EXISTS elective_positions;
DROP TABLE IF EXISTS elections;
DROP TABLE IF EXISTS polling_stations;
DROP TABLE IF EXISTS wards;
DROP TABLE IF EXISTS constituencies;
DROP TABLE IF EXISTS counties;
DROP TABLE IF EXISTS party_memberships;
DROP TABLE IF EXISTS coalition_members;
DROP TABLE IF EXISTS coalitions;
DROP TABLE IF EXISTS political_parties;
DROP TABLE IF EXISTS politicians;
DROP TABLE IF EXISTS sources;

DROP EXTENSION IF EXISTS "pg_trgm";
DROP EXTENSION IF EXISTS "uuid-ossp";
